<?php

function getZip($userID)
{

	$query="SELECT zipCode FROM users WHERE userID = '$userID';";
	$zipCode=mysql_query($query);
	$zipCode=mysql_fetch_row($zipCode);
	$zipCode=$zipCode[0];
	return $zipCode;
}

function getAreaCourses($zipCode)
{
	$query="SELECT courseID, name, length, difficulty, mapLink,
			CASE 
				WHEN TIMESTAMPDIFF(MINUTE, dateAdded,CURRENT_TIMESTAMP()) < 60 THEN TIMESTAMPDIFF(MINUTE, dateAdded,CURRENT_TIMESTAMP()) 
				WHEN TIMESTAMPDIFF(MINUTE, dateAdded,CURRENT_TIMESTAMP()) >= 60 AND TIMESTAMPDIFF(MINUTE, dateAdded,CURRENT_TIMESTAMP()) < 1440 THEN TIMESTAMPDIFF(HOUR, dateAdded,CURRENT_TIMESTAMP())
				WHEN TIMESTAMPDIFF(MINUTE, dateAdded,CURRENT_TIMESTAMP()) >= 1440 AND TIMESTAMPDIFF(MINUTE, dateAdded,CURRENT_TIMESTAMP()) < 46080 THEN TIMESTAMPDIFF(DAY, dateAdded,CURRENT_TIMESTAMP())
				WHEN TIMESTAMPDIFF(MINUTE, dateAdded,CURRENT_TIMESTAMP()) >= 46080 AND TIMESTAMPDIFF(MINUTE, dateAdded,CURRENT_TIMESTAMP()) < 416100 THEN TIMESTAMPDIFF(MONTH, dateAdded,CURRENT_TIMESTAMP())
				WHEN TIMESTAMPDIFF(MINUTE, dateAdded,CURRENT_TIMESTAMP()) >= 416100 THEN TIMESTAMPDIFF(YEAR, dateAdded,CURRENT_TIMESTAMP())
			END AS timeAgo,
			CASE 
				WHEN TIMESTAMPDIFF(MINUTE, dateAdded,CURRENT_TIMESTAMP()) < 60 THEN 'mins'
				WHEN TIMESTAMPDIFF(MINUTE, dateAdded,CURRENT_TIMESTAMP()) >= 60 AND TIMESTAMPDIFF(MINUTE, dateAdded,CURRENT_TIMESTAMP()) < 1440 THEN 'hrs'
				WHEN TIMESTAMPDIFF(MINUTE, dateAdded,CURRENT_TIMESTAMP()) >= 1440 AND TIMESTAMPDIFF(MINUTE, dateAdded,CURRENT_TIMESTAMP()) < 46080  THEN 'days'
				WHEN TIMESTAMPDIFF(MINUTE, dateAdded,CURRENT_TIMESTAMP()) >= 46080 AND TIMESTAMPDIFF(MINUTE, dateAdded,CURRENT_TIMESTAMP()) < 416100  THEN 'months'
				WHEN TIMESTAMPDIFF(MINUTE, dateAdded,CURRENT_TIMESTAMP()) >= 416100 THEN 'years'
			END AS periodAgo
			FROM courses WHERE zipCode = $zipCode
			ORDER BY TIMESTAMPDIFF(MINUTE, dateAdded,CURRENT_TIMESTAMP()) LIMIT 3";
	$result=mysql_query($query);
	return $result;
}

function courseActivity($userID)
{
	$query="SELECT runs.runID, users.username, courses.name, courses.mapLink, TIMEDIFF( runs.endTime, runs.startTime ) AS time,
			CASE 
				WHEN TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) < 60 THEN TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) 
				WHEN TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) >= 60 AND TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) < 1440 THEN TIMESTAMPDIFF(HOUR, dateAdded,CURRENT_TIMESTAMP())
				WHEN TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) >= 1440 AND TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) < 46080 THEN TIMESTAMPDIFF(DAY, dateAdded,CURRENT_TIMESTAMP())
				WHEN TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) >= 46080 AND TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) < 416100 THEN TIMESTAMPDIFF(MONTH, dateAdded,CURRENT_TIMESTAMP())
				WHEN TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) >= 416100 THEN TIMESTAMPDIFF(YEAR, runs.endTime,CURRENT_TIMESTAMP())
			END AS timeAgo,
			CASE 
				WHEN TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) < 60 THEN 'mins'
				WHEN TIMESTAMPDIFF(MINUTE, runs.endtime,CURRENT_TIMESTAMP()) >= 60 AND TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) < 1440 THEN 'hrs'
				WHEN TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) >= 1440 AND TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) < 46080  THEN 'days'
				WHEN TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) >= 46080 AND TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) < 416100  THEN 'months'
				WHEN TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) >= 416100 THEN 'years'
			END AS periodAgo 
			FROM runs
			JOIN courses ON courses.courseID = runs.courseID
			JOIN users ON runs.userID = users.userID
			WHERE courses.userID = '$userID' AND runs.userID != '$userID'
			ORDER BY TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) LIMIT 3;";
	$results=mysql_query($query);
	return $results;
}

function friendsFeed($userID)
{
	$query="SELECT users.username, runs.runID, courses.name, courses.mapLink, TIMEDIFF( runs.endTime, runs.startTime ) AS time, 		CASE 
				WHEN TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) < 60 THEN TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) 
				WHEN TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) >= 60 AND TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) < 1440 THEN TIMESTAMPDIFF(HOUR, dateAdded,CURRENT_TIMESTAMP())
				WHEN TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) >= 1440 AND TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) < 46080 THEN TIMESTAMPDIFF(DAY, dateAdded,CURRENT_TIMESTAMP())
				WHEN TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) >= 46080 AND TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) < 416100 THEN TIMESTAMPDIFF(MONTH, dateAdded,CURRENT_TIMESTAMP())
				WHEN TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) >= 416100 THEN TIMESTAMPDIFF(YEAR, runs.endTime,CURRENT_TIMESTAMP())
			END AS timeAgo,
			CASE 
				WHEN TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) < 60 THEN 'mins'
				WHEN TIMESTAMPDIFF(MINUTE, runs.endtime,CURRENT_TIMESTAMP()) >= 60 AND TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) < 1440 THEN 'hrs'
				WHEN TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) >= 1440 AND TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) < 46080  THEN 'days'
				WHEN TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) >= 46080 AND TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) < 416100  THEN 'months'
				WHEN TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) >= 416100 THEN 'years'
			END AS periodAgo 
			FROM friendships
			JOIN users ON friendships.secondUser = users.userID
			JOIN runs ON users.userID = runs.userID
			JOIN courses ON runs.courseID = courses.courseID
			WHERE friendships.firstUser = '$userID'
			ORDER BY TIMESTAMPDIFF(MINUTE, runs.endTime,CURRENT_TIMESTAMP()) LIMIT 3;";
	$results=mysql_query($query);
	return $results;
}


?>